### ISSUE TITLE
How to filter out only windows in workspace 1?

### ISSUE THREAD

**Issue by tmpm697** [AdrienLeGuillou/sway_window_swithcher_dmenu#1]
Hi, how can I filter out only windows in a specific workspace (workspace 1 for e.g), as I don't want to list windows in all workspaces.

**Comment by AdrienLeGuillou** [comment]
You would need to change the script. I botched this one a while ago and I don't use it anymore. Adding the workspace should not be to complex when you are familiar with sway message API. Unfortunately I don't have time to implement it myself

**Comment by tmpm697** [comment]
I tried to add `.workspace == 1` to this line:  https://github.com/AdrienLeGuillou/sway_window_swithcher_dmenu/blob/329a6462d06d45ee72f7836f67fe4c67418fad9a/sws.sh#L119 but it gives empty result.

**Comment by AdrienLeGuillou** [comment]
I encourage you to play around with `jq` and the types of messages sway returns. It's a bit tricky at first

**Comment by tmpm697** [comment]
I played with it and google around half of day and still not found a way to filter out only a specific workspace.

I have to pass the first jq to this one : `| jq 'select(.workspace == "1")'` to have it work but that will break format. Can you give a check?

**Comment by AdrienLeGuillou** [comment]
I cannot, it took me a while to understand how all of it worked and it was a long time ago. I do not have the time nor the desire to maintain this project anymore. I left it on GH only as it could be of use for some people as is or as a starting point.

Sorry

**Comment by tmpm697** [comment]
Found a way, thanks for sharing.
